### ISSUE TITLE
Author name confused with protein family

### ISSUE THREAD

**Issue by ozgunbabur** [clulab/reach#499] opened 2017-03-30 00:29 UTC
In the below REACH output from PMC3533183, we see the author name (Lim et al.) is confused with the protein family name Lim. The "XREF_BIBR" in the sentence shows REACH has already recognized that part as a paper reference. But looks like it is still considered as an entity name.

```
        {
            "predicate": {
                "id": "evem-PMC3533183-UAZ-r1-3533183-106-54",
                "type": "regulation",
                "event_text": "PML phosphorylation at Ser403 and Ser505 is detectable in unstimulated cells and can also be further induced by EGF stimulation (Lim",
                "sign": "positive",
                "sub_type": "positive-regulation"
            },
            "participant_a": [
                {
                    "entity_text": "Lim",
                    "entity_type": "family",
                    "identifier": "pfam:PF00412"
                }
            ],
            "participant_b": [
                {
                    "predicate": {
                        "id": "evem-PMC3533183-UAZ-r1-3533183-106-53",
                        "type": "protein-modification",
                        "event_text": "PML phosphorylation at Ser403 and Ser505",
                        "sign": "positive",
                        "sub_type": "phosphorylation",
                        "is-hypothesis": true
                    },
                    "participant_b": [
                        {
                            "entity_text": "PML",
                            "entity_type": "protein",
                            "identifier": "uniprot:P29590"
                        }
                    ],
                    "sentence": "Basal PML phosphorylation at Ser403 and Ser505 is detectable in unstimulated cells and can also be further induced by EGF stimulation ( Lim et al. , XREF_BIBR ) , implying that this mechanism regulates PML levels under steady-state and inducible conditions .",
                    "sites": [
                        {
                            "site_text": "Ser505",
                            "identifier": "UAZ-S-016",
                            "amino_acid": "serine",
                            "position": "505"
                        }
                    ]
                }
            ],
            "sentence": "Basal PML phosphorylation at Ser403 and Ser505 is detectable in unstimulated cells and can also be further induced by EGF stimulation ( Lim et al. , XREF_BIBR ) , implying that this mechanism regulates PML levels under steady-state and inducible conditions ."
        },
```

**Comment by hickst** [comment] 2017-04-16 15:47
I confirmed that this problem still exists in the current version of Reach. The input NXML file is attached (with a spurious `.txt` extension, as demanded by GitHub).
[PMC3533183.nxml](https://github.com/clulab/reach/files/924389/PMC3533183.nxml.txt)

**Comment by MihaiSurdeanu** [comment] 2017-04-19 23:36
@hickst: this happens because we do not remove citations that are not properly marked in the NXML. However, we should handle this in BioNLPPreProcessor:

https://github.com/clulab/processors/blob/master/corenlp/src/main/scala/org/clulab/processors/bionlp/BioNLPPreProcessor.scala

We need a function similar to removeFigureAndTableReferences().

**Comment by hickst** [comment] 2017-04-21 00:46
@mihai Sorry, that's a bit ambiguous: should I remove all parenthesized expressions containing xrefs of type "bibr" or are there some citations that are "properly marked" and which should not be removed?

**Comment by MihaiSurdeanu** [comment] 2017-04-21 14:54
All citations should be removed. Text in parens confuses the parser.

**Comment by hickst** [comment] 2017-04-22 18:34
Closed by Processors pull requests 146 (fix) and 147 (tests).

**Closed by hickst** 2017-04-22 18:34 UTC
Labels: bug
