### ISSUE TITLE
Strange behavior with thread-limited parallelization 

### ISSUE THREAD

**Issue by myedibleenso** [clulab/reach#570] opened 2017-11-30 04:13 UTC
Based on behavior observed in a recent run, @danebell reported that `reach` doesn't seem to be making use of the `nThreads` configuration property.  With the switch to the Akka client-server system, are we being trumped by a hard-coded limit elsewhere, @hickst?

**Comment by hickst** [comment] 2017-11-30 06:53
No, we can't blame Akka for this: it was a problem before that....see issue #528 
I think this issue is a duplicate of that one and I'm gonna mark this as 'duplicate' and close it. (Feel free to re-open it if it really isn't the same problem).

**Closed by hickst** 2017-11-30 06:53 UTC
Labels: bug, duplicate
