### ISSUE TITLE
windows friendliness

### ISSUE THREAD

**Issue by marcovzla** [clulab/reach#512] opened 2017-05-25 21:41 UTC
replace `${HOME}` with `${user.home}` in config files

**Comment by marcovzla** [comment] 2017-05-25 21:59
also seen on windows:

```
Loading ReachSystem ...
[error] (run-main-0) java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
        at org.clulab.reach.grounding.ReachEntityLookup$$anonfun$org$clulab$reach$grounding$ReachEntityLookup$$addAdHocFile$1.apply(ReachEntityLookup.scala:35)
        at org.clulab.reach.grounding.ReachEntityLookup$$anonfun$org$clulab$reach$grounding$ReachEntityLookup$$addAdHocFile$1.apply(ReachEntityLookup.scala:33)
        at scala.Option.map(Option.scala:146)
        at org.clulab.reach.grounding.ReachEntityLookup.org$clulab$reach$grounding$ReachEntityLookup$$addAdHocFile(ReachEntityLookup.scala:33)
        at org.clulab.reach.grounding.ReachEntityLookup$$anonfun$1.apply(ReachEntityLookup.scala:79)
        at org.clulab.reach.grounding.ReachEntityLookup$$anonfun$1.apply(ReachEntityLookup.scala:79)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
        at org.clulab.reach.grounding.ReachEntityLookup.<init>(ReachEntityLookup.scala:79)
        at org.clulab.reach.ReachSystem.<init>(ReachSystem.scala:35)
        at org.clulab.reach.ReachShell$.delayedEndpoint$org$clulab$reach$ReachShell$1(ReachShell.scala:25)
        at org.clulab.reach.ReachShell$delayedInit$body.apply(ReachShell.scala:14)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at org.clulab.reach.ReachShell$.main(ReachShell.scala:14)
        at org.clulab.reach.ReachShell.main(ReachShell.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:159)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at java.util.zip.CheckedInputStream.read(CheckedInputStream.java:59)
        at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:266)
        at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
        at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at org.clulab.reach.grounding.ReachKBUtils$.sourceFromResource(ReachKBUtils.scala:66)
        at org.clulab.reach.grounding.TsvIMKBFactory.org$clulab$reach$grounding$TsvIMKBFactory$$loadFromKBDir(TsvIMKBFactory.scala:45)
        at org.clulab.reach.grounding.TsvIMKBFactory$$anonfun$make$1.apply(TsvIMKBFactory.scala:23)
        at org.clulab.reach.grounding.TsvIMKBFactory$$anonfun$make$1.apply(TsvIMKBFactory.scala:22)
        at scala.Option.foreach(Option.scala:257)
        at org.clulab.reach.grounding.TsvIMKBFactory.make(TsvIMKBFactory.scala:22)
        at org.clulab.reach.grounding.ReachIMKBMentionLookups$.contextCellLineKBML(ReachIMKBMentionLookups.scala:246)
        at org.clulab.reach.grounding.ReachIMKBMentionLookups$.<init>(ReachIMKBMentionLookups.scala:21)
        at org.clulab.reach.grounding.ReachIMKBMentionLookups$.<clinit>(ReachIMKBMentionLookups.scala)
        at org.clulab.reach.grounding.ReachEntityLookup$$anonfun$org$clulab$reach$grounding$ReachEntityLookup$$addAdHocFile$1.apply(ReachEntityLookup.scala:35)
        at org.clulab.reach.grounding.ReachEntityLookup$$anonfun$org$clulab$reach$grounding$ReachEntityLookup$$addAdHocFile$1.apply(ReachEntityLookup.scala:33)
        at scala.Option.map(Option.scala:146)
        at org.clulab.reach.grounding.ReachEntityLookup.org$clulab$reach$grounding$ReachEntityLookup$$addAdHocFile(ReachEntityLookup.scala:33)
        at org.clulab.reach.grounding.ReachEntityLookup$$anonfun$1.apply(ReachEntityLookup.scala:79)
        at org.clulab.reach.grounding.ReachEntityLookup$$anonfun$1.apply(ReachEntityLookup.scala:79)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
        at org.clulab.reach.grounding.ReachEntityLookup.<init>(ReachEntityLookup.scala:79)
        at org.clulab.reach.ReachSystem.<init>(ReachSystem.scala:35)
        at org.clulab.reach.ReachShell$.delayedEndpoint$org$clulab$reach$ReachShell$1(ReachShell.scala:25)
        at org.clulab.reach.ReachShell$delayedInit$body.apply(ReachShell.scala:14)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at org.clulab.reach.ReachShell$.main(ReachShell.scala:14)
        at org.clulab.reach.ReachShell.main(ReachShell.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last root/compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last root/compile:runMain for the full output.
[error] (root/compile:runMain) Nonzero exit code: 1
[error] Total time: 2 s, completed May 25, 2017 2:42:44 PM
```

**Comment by hickst** [comment] 2017-05-25 23:37
I haven't programmed on Windows in 25 years but the first message looks like you it is telling you to substitute the Windows 'user.home' variable for all uses of Unix 'HOME' variable. A quick grep of Reach shows that HOME is only used in the main/src/main/resources/application.conf and main/src/main/resources/application.conf files to setup the paths to documents and KB files. The bad paths to those documents are most likely the cause of the second errors.

**Comment by hickst** [comment] 2017-05-25 23:39
I haven't programmed on Windows in 25 years but the first message looks like it is telling you to substitute the Windows 'user.home' variable for all uses of Unix 'HOME' variable. A quick grep of Reach shows that HOME is only used in the main/src/main/resources/application.conf and assembly/src/main/resources/reference.conf files to setup the paths to documents and KB files. The bad paths to those documents are most likely the cause of the second errors.

**Comment by marcovzla** [comment] 2017-05-26 19:19
These two problems are unrelated. Reach doesn't work on windows if the home variable used is `${HOME}`. I replaced it to `${user.home}` so that it runs, but now I am getting the exception I pasted above.

**Comment by hickst** [comment] 2017-05-26 19:29
More information....which version of Java?

**Comment by marcovzla** [comment] 2017-05-26 20:16
1.8.0_91-b14

**Comment by marcovzla** [comment] 2017-05-26 20:18
windows ☹️

**Comment by hickst** [comment] 2017-05-26 21:46
I still think the problems are related. This is the type of error that might be expected if the grounding code of Reach cannot find the KB files to load on startup. The initial error indicated that they couldn't be found because of the HOME variable but maybe they still can't be found via the config path OR they can't be found because of some other path/file reading problem...

**Comment by hickst** [comment] 2017-05-30 18:28
MS says Windows version is of very low importance, so closing this issue as "unsolved" for now.

**Closed by hickst** 2017-05-30 18:28 UTC
Labels: unsolved
