### ISSUE TITLE
${eventName}_syntax_1_verb not matching

### ISSUE THREAD

**Issue by marcovzla** [clulab/reach#223] opened 2016-06-07 18:48 UTC
Why is rule `${eventName}_syntax_1_verb` not matching in this sentence?

    E3 ubiquitin protein ubiquitinates  beta-catenin.

**Comment by myedibleenso** [comment] 2016-06-07 19:17
For reference:
```yaml
- name: ${ eventName }_syntax_1_verb
  priority: ${ priority }
  example: "We further showed, in a combined enzymatic assay, that human deoxycytidine kinase and UMP-CMP kinase together ${ verbalTriggerLemma }d araC, dFdC, and 2',3'-dideoxycytidine to their diphosphate forms."
  label: ${ label }
  action: ${ actionFlow }
  pattern: |
    trigger = [lemma=/${ verbalTriggerLemma }/ & ${triggerPrefix} & tag=/^(V|JJ)/ & !mention=ModificationTrigger]
    cause:BioChemicalEntity? = <xcomp? (nsubj | agent | <vmod) /appos|nn|conj_(and|or|nor)|cc/{,2}
    theme:BioChemicalEntity = (dobj | xcomp) /conj_(and|or|nor)|dep|cc|nn|prep_of/{,2} (>> [word=by]){,2}
    site:Site? = dobj? /prep_(at|on)|nn|conj_(and|or|nor)|cc/{,2}
```

Template instantiation:

```yaml
  # Ubiquitination
  - import: edu/arizona/sista/reach/biogrammar/events/simple-event_template.yml
    vars:
      eventName: "Ubiquitination"
      actionFlow: "mkUbiquitination"
      label: "Ubiquitination"
      verbalTriggerLemma: "ubiquitinate"
      nominalTriggerLemma: "ubiquitination"
      triggerPrefix: "!word=/(?i)^de/"
      priority: "5"
```

**Comment by danebell** [comment] 2016-06-07 19:18
`E3` is recognized, and so is `ubiquitin`, but not `E3 ubiquitin protein` isn't. `E3` is typed a cell line, and ubiquitin can't be the cause of a ubiquitination, so neither one is a good cause. 

Not sure how to fix this. I'll look into it, but I'm open to suggestions in the meantime.

**Comment by MihaiSurdeanu** [comment] 2016-06-07 19:21
But the cause in that rule has the optional nn, so it should "jump" over
protein, no?

**Comment by marcovzla** [comment] 2016-06-07 19:21
i don't think this works either: "E3 ubiquitin ligase ubiquitinates  beta-catenin."

**Comment by danebell** [comment] 2016-06-07 19:28
Aha! The cause of a ubiquitination can't contain the string `ubiq`.
>mentions.filterNot { ev => ev.arguments.get("cause").map(_.exists(_.text.toLowerCase.contains("ubiq"))).getOrElse(false) }

I'll amend that.

**Comment by danebell** [comment] 2016-06-09 18:16
`E3 ubiquitin protein` probably _shouldn't_ be recognized -- `E3 ubiquitin ligase` is correct. The latter is now recognized as a possible cause for a ubiquitination, so I am closing this issue.

**Closed by danebell** 2016-06-09 18:16 UTC
