### ISSUE TITLE
Errors arising from binding11_token rule

### ISSUE THREAD

**Issue by johnbachman** [clulab/reach#495] opened 2017-03-14 18:30 UTC
Hi guys, just anecdotally I found a few errors with this rule--in all of the below cases it takes a fragment referring to the "association between KRAS and BRAF mutations" to extract a statement that "KRAS binds BRAF." (KRAS *does* bind BRAF, so these extractions happen to be right but for the wrong reason.)

PMID20147967:  "Recent clinical data has shown a compelling association between K-Ras and B-Raf mutation status and response to EGFR blockade by cetuximab and panitumumab in the treatment of metastatic colorectal tumours (Benvenuti et al, 2007; Khambata-Ford et al, 2007; Freeman et al, 2008; Karapetis et al, 2008; Ramos et al, 2008)."

PMID23157823: "To identify the mutation rate of KRAS and BRAF in Chinese patients with colorectal carcinoma (CRC), and to analyze the associations between KRAS and BRAF mutations and patients ' clinicopathological characteristics."

PMID20233436, "This study investigates the associations between BRAF and K-ras mutations and clinicopathological, lifestyle and dietary factors in colorectal cancers."

**Comment by MihaiSurdeanu** [comment] 2017-03-14 21:27
@johnbachman: thanks!

Should we disable "association between A and B" as a Binding rule?

**Comment by johnbachman** [comment] 2017-03-15 15:13
I will try taking a look at a sample of statements extracted by that rule and see what it's accuracy is more generally.

**Comment by MihaiSurdeanu** [comment] 2017-03-15 15:16
Thanks!
We definitely saw this rule perform well, especially for verbal predicates ("A associates with B").

**Comment by bgyori** [comment] 2017-03-15 15:18
I think this points to a more general issue that we discussed in #325 and I don't think it's specific to `association`. The issue, I think, is that the statement `the associations between KRAS and BRAF mutations` is not actually about `BRAF`, but about `BRAF mutations`. A similar omission leads to incorrect extractions in the examples I gave in #325.

**Comment by MihaiSurdeanu** [comment] 2017-03-15 15:36
@bgyori: I agree.

@danebell: Ben's example should be captured by your mutation rules + coref for mutations. Can you please check what's wrong?

**Comment by MihaiSurdeanu** [comment] 2017-03-15 15:37
@bgyori, @johnbachman: but beyond the mutation mistakes, is the pattern "association between A and B" actually indicating a Binding event? I think that is a separate question.

**Comment by bgyori** [comment] 2017-03-16 00:29
I think "association between A and B" does indicate physical interaction, for instance a real example is "The association between EGF and EGFR induces conformational changes...". One just has to be very sure that A and B are genes and not other, more complicated noun phrases that just contain a gene name.

**Comment by danebell** [comment] 2017-03-20 16:08
I don't think I was able to recreate this wrong extraction. That is, we do retrieve a binding between KRAS and BRAF in each case, and each time, the entity immediately preceding "mutations" is marked as a generic mutant (one we don't know the specific mutation(s) of). Should we remove events that involve such mutants, or is the mutation modification not making into your format of interest?

**Comment by bgyori** [comment] 2017-03-20 16:18
Dane, the issue is that the sentence "To identify the mutation rate of KRAS and BRAF in Chinese patients with colorectal carcinoma (CRC), and to analyze the **associations between KRAS and BRAF mutations** and patients ' clinicopathological characteristics"
isn't actually about KRAS and BRAF **binding**. It talks about a statistical association between **mutations**. So extracting that KRAS and BRAF binds is the issue.

**Comment by danebell** [comment] 2017-03-20 16:37
Ah, I see. My first guess is that we should check for a conjunction between entities and non-entities, e.g. between `KRAS` and `patients' clinicopathological characteristics`, and if we find one, rule out a binding event. Does that sound reliable to you?

How about the counter-example, "This work investigations association between KRAS and BRAF and resulting effects on downstream apoptosis." inserting appropriate entities for `KRAS` and `BRAF` so that we would expect them to bind and affect apoptosis? I am just struggling to know how we can reliably know when we have a binding. Perhaps what you mention above, that we don't have genes?

I think could only apply to the trigger of `association(s)`. Am I right in this?

**Comment by MihaiSurdeanu** [comment] 2017-04-19 23:44
@bgyori, @johnbachman: so, what's the conclusion here?

**Comment by bgyori** [comment] 2017-04-19 23:50
All I can say is that I still think problem can be reduced to #325. It is not a problem with the interpretation of "association" itself but rather with the fact that association is between A and B **mutations** rather than A and B (where A and B are two proteins).

**Comment by MihaiSurdeanu** [comment] 2017-04-19 23:59
Syntactically, they look similar, but semantically they are different... What is the exact biology for the text "association between KRAS and BRAF mutations"? I'm not sure I get it...

**Comment by bgyori** [comment] 2017-04-20 00:04
It's not really about a biological mechanism at all but more about _statistical_ association. 

For instance "Recent clinical data has shown a compelling association between K-Ras and B-Raf mutation status and response to EGFR blockade by cetuximab and panitumumab" means that there is some correlation between whether a patient has K-Ras and/or B-Raf mutation and whether the patient responds to drugs that target EGFR.

"analyze the associations between KRAS and BRAF mutations and patients ' clinicopathological characteristics" I think means studying the statistical relationship between whether a patient has KRAS and/or BRAF mutation and the characteristics and outcome of their disease.

**Comment by danebell** [comment] 2017-04-26 23:30
Closed with pull request #507

**Closed by danebell** 2017-04-26 23:30 UTC
Labels: bug
