### ISSUE TITLE
Missing log file for debugging ReachCLI issues

### ISSUE THREAD

**Issue by johnbachman** [clulab/reach#463] opened 2016-12-06 15:10 UTC
Hi there,

Lately I've had some issues running large reading jobs on Amazon (using the ReachCLI) where the job seems to just halt in the middle of a set of papers. Running "top" indicates that java is still running, but output from standard out stops and no new output .json files are produced.

The output to standard out looks normal, here are the last few lines:

```
INFO: indra/runreach - b'03:21:56.158 [ForkJoinPool-1-worker-21] INFO  org.clulab.reach.ReachCLI - Tue Dec 06 03:21:56 UTC 2016: Starting PMID22840454\n'
INFO: indra/runreach - b'\n'
INFO: indra/runreach - b'03:21:56.330 [ForkJoinPool-1-worker-27] INFO  org.clulab.reach.ReachCLI - Tue Dec 06 03:21:56 UTC 2016: Finished PMID22194952 successfully (34 seconds)\n'
INFO: indra/runreach - b'\n'
INFO: indra/runreach - b'03:21:56.330 [ForkJoinPool-1-worker-27] INFO  org.clulab.reach.ReachCLI - Tue Dec 06 03:21:56 UTC 2016: Starting PMID19617705\n'
INFO: indra/runreach - b'\n'
INFO: indra/runreach - b'03:21:57.824 [ForkJoinPool-1-worker-27] INFO  org.clulab.reach.ReachCLI - Tue Dec 06 03:21:57 UTC 2016: Finished PMID19617705 successfully (1 seconds)\n'
INFO: indra/runreach - b'\n'
INFO: indra/runreach - b'03:21:57.824 [ForkJoinPool-1-worker-27] INFO  org.clulab.reach.ReachCLI - Tue Dec 06 03:21:57 UTC 2016: Starting PMID15979856\n'
INFO: indra/runreach - b'\n'
```

I want to inspect the REACH log file to see if there are any error messages that I'm missing, but it doesn't look like it's being generated, even though I have logging enabled in my .conf file. I wasn't sure which way to specify the path to the log file, so I left both blocks in there. Is that what is causing the problem? Neither of the files pointed to by the relevant variables are being produced. 

Here is my entire .conf file:

```
#
# Configuration file for reach
#

# this is the directory that stores the raw nxml, .csv, and/or .tsv files
# this directory *must* exist
papersDir = tmpdir_target3/read_0_to_137004_rvu5xg/input

# this is where the output files containing the extracted mentions will be stored
# if this directory doesn't exist it will be created
outDir = tmpdir_target3/read_0_to_137004_rvu5xg/output

# the output format for mentions: text, fries, indexcard, or assembly-csv (default is 'fries')
outputType = "fries"

# whether or not assembly should be run
withAssembly = false

# this is where the context files will be stored
# if this directory doesn't exist it will be created
contextDir = tmpdir_target3/read_0_to_137004_rvu5xg/output

# this is where the brat standoff and text files are dumped
bratDir = tmpdir_target3/read_0_to_137004_rvu5xg/output

# verbose logging
verbose = true

# the encoding of input and output files
encoding = "utf-8"


# this is a list of sections that we should ignore
ignoreSections = ["references", "materials", "materials|methods", "methods", "supplementary-material"]

# context engine config
contextEngine {
    type = Policy4
    params = {
        bound = 3
    }
}

logging {
  # defines project-wide logging level
  loglevel = INFO
  logfile = tmpdir_target3/read_0_to_137004_rvu5xg/reach.log
}

# this log file gets overwritten every time ReachCLI is executed
# so you should copy it if you want to keep it around
logFile = tmpdir_target3/read_0_to_137004_rvu5xg/log.txt

# grounding configuration
grounding: {
  # List of AdHoc grounding files to insert, in order, into the grounding search sequence.
  # Each element of the list is a map of KB filename and optional meta info (not yet used):
  #   example: { kb: "adhoc.tsv", source: "NMZ at CMU" }
  adHocFiles: [
    { kb: "NER-Grounding-Override.tsv.gz", source: "MITRE/NMZ/BG feedback overrides" }
  ]

  # flag to turn off the influence of species on grounding
  overrideSpecies = true
}

# number of simultaneous threads to use for parallelization
threadLimit = 32

# ReadPapers
ReadPapers.papersDir = src/test/resources/inputs/nxml/
ReadPapers.serializedPapers = mentions.ser
```

**Comment by hickst** [comment] 2016-12-06 16:18
I've never used AWS John, but you should not have the second 'logFile' entry: just keep the logging section.

Otherwise, the usual caveats apply: e.g., your process must have correct permissions (write) on the output directories. Make sure you run with as much RAM as you can manage: an absolute minimum of 8G.

Are standard output and standard error redirected somewhere by AWS? You might try finding and examining those output streams to see if any information is produced there.

As to the apparent stalling: I think you are encountering issue #426. We have yet to ascertain why some files (mostly larger files, but not always) take an inordinate amount of time. We have actually seen some files (usually > 750k+) take up to 8 hours to finish.

Finally, if you can send us the file, we can try running it here and see if we are encountering the same problems.

**Comment by johnbachman** [comment] 2016-12-06 16:30
I doubt it's just long runtime on certain files for at least two reasons:

1) We're talking about a 12 hour gap since the last output was produced and when I checked on the process.

2) When I restart the job on the remaining papers, it continues to run.

Write access should be OK since the program is writing out the .json files to the output directory--presumably the logger would have the same permissions.

I could take a look to see which files were started but not finished at the time of the last entries to stdout to see if there are any particular problematic files.

**Comment by hickst** [comment] 2016-12-06 16:50
Yes, please try to identify the problem files and we can run a couple here as a test.

**Comment by hickst** [comment] 2016-12-11 17:48
@johnbachman Hi John, are you still having problems with certain files? Have to managed to identify any specific problematic files? Did increasing memory help with those files?

**Comment by hickst** [comment] 2017-01-24 19:59
@johnbachman Hi John, are you still having problems with certain files? Have you managed to identify any specific problematic files? Did increasing memory help with those files?

**Comment by johnbachman** [comment] 2017-01-25 16:15
Hi Tom, I just did a big run last weekend and again had some issues where
the processes would freeze up and have to be restarted. I still also
haven't been able to generate a log file (just a dump of standard out). I
will try again to see if it happens on specific files.

**Comment by hickst** [comment] 2017-01-25 16:42
I don't understand the missing log file as, by default, the application.conf will produce a log file `reach.log` in the root directory. By any chance, are you adding Reach to some other software which overrides the Log4j configuration?

You should try the latest master Reach, as we have recently changed the application.conf file to, by default, use a single root directory (from which all other directories are derived) AND added the ability to restart crashed runs without reprocessing files which finished successfully.

**Comment by johnbachman** [comment] 2017-01-30 20:17
Hi, so I'm still not able to see the log file. I changed the permissions on the temporary directory I'm creating to be world-writeable to see if that would fix it, but not luck.

Also, here are a few papers that took a long time in the most recent run, though they did eventually finish::

```
Finished PMID27345422 successfully (675 seconds)\n'
Finished PMID27521218 successfully (779 seconds)\n'
Finished PMID27630114 successfully (603 seconds)\n'
```

**Comment by myedibleenso** [comment] 2017-01-30 20:21
@johnbachman, regarding the slow processing time, did you run these papers with the latest version of reach (38d2c4330e2ec8064a2829288a3c7b42b844eeef)?  While the last PR that was merged isn't supposed to change output, it should vastly improve runtime on some papers.  I'm curious if that is/was the problem with the papers you've referenced...

**Comment by johnbachman** [comment] 2017-01-30 20:23
Yes, these were run with the version 38d2c4330, updated today.

**Comment by myedibleenso** [comment] 2017-01-30 20:29
Thanks. We'll open an issue and start exploring the cause.

**Comment by johnbachman** [comment] 2017-01-31 16:56
Just as an update, I ran REACH on a corpus of ~100k papers last night without it freezing up--so it could be that the latest PR fixed the underlying problem. I have a larger corpus of 270k papers that was causing a lot of problems before, will try that one next and report back.

**Comment by MihaiSurdeanu** [comment] 2017-01-31 16:58
Awesome!

**Comment by hickst** [comment] 2017-04-22 18:37
@johnbachman How did the tests go? Can we close this issue?

**Comment by johnbachman** [comment] 2017-05-06 02:38
Hi, so I just did another large reading job and I had one paper that caused REACH to hang--it was text extracted from Elsevier so it's a bit garbled. The paper is PMID17032502, I sent the text to @hickst by email to keep it out of the public domain. I saw a few others that caused REACH to issue errors but I'll have to go through the logs to find them all.

**Closed** 2017-12-09 02:11 UTC
