### ISSUE TITLE
missing event annotations

### ISSUE THREAD

**Issue by guerrerosimonl** [clulab/reach#645] opened 2019-12-12 12:30 UTC
I tried to figure out if it is possible to add manually new annotations but I still don't completely understand how it works so there it goes my question:

I found that there are some compounds that REACH cannot identify (because they are not annotated). In my case, I need to process a few papers which main subject is the chemical "lindane". I found out that its synonym "gamma-HCH" is annotated, but not the word lindane, which many papers use instead of gamma-HCH. Is there any solution for this? 

Thank you!

**Comment by MihaiSurdeanu** [comment] 2019-12-12 16:41
Yes, this is possible without writing actual code.

The list of known entities are stored and managed in this project:
https://github.com/clulab/bioresources

In particular, the actual entities, organized by type are here:
https://github.com/clulab/bioresources/tree/master/src/main/resources/org/clulab/reach/kb

You probably should add the missing chemical to the PubChem.tsv.gz file (which stores chemical compounds extracted from PubChem), or to NER-Grounding-Override.tsv.gz, which stores "overriding" entities that are missing in the corresponding larger files.

Once you add the missing entities, please send us a PR. Then, we will release this project, and update the dependencies in Reach. This should be it...

**Comment by guerrerosimonl** [comment] 2019-12-13 13:57
Hi! 

Thank you very much for your fast answer.I'm new using GitHub, so I really didn't know in which branch I had to upload the file while doing the PR. I'm sorry! Here it is the updated PubChem.tsv.gz.

[PubChem.tsv.gz](https://github.com/clulab/reach/files/3961076/PubChem.tsv.gz)

Laura

**Comment by MihaiSurdeanu** [comment] 2019-12-13 19:35
I added this file to the bioresources project.
I am about to leave on a trip, so I don't have the time to release these projects now.
@kwalcock: when you get a chance can you please release bioresources 1.1.26 to maven? Then update main/build.sbt in reach to this new version? And, ideally, check that unit tests still pass :)

Thanks a lot!

**Comment by kwalcock** [comment] 2019-12-13 19:49
Acknowledged.  It may be a couple days before the chance arrives.

**Comment by guerrerosimonl** [comment] 2019-12-16 08:20
Thank you so much to both of you!

Please, can you let me know when it is released? 

Laura

**Comment by kwalcock** [comment] 2019-12-19 04:22
If anyone is waiting on this task (@guerrerosimonl), please be advised that it has been completed.

**Comment by kwalcock** [comment] 2019-12-19 04:23
Addressed with #647.

**Comment by Hasnae-25** [comment] 2020-01-22 10:56
Hi all, I am very new using Github. Can someone release this project?

Thanks in advance!

Kind regards, Hasnae

[PubChem.tsv.gz](https://github.com/clulab/reach/files/4096690/PubChem.tsv.gz)

**Comment by MihaiSurdeanu** [comment] 2020-01-22 12:30
@kwalcock: can you please indicate what version number corresponds to this?
Thanks!

**Comment by kwalcock** [comment] 2020-01-22 15:35
This file is the same as what is in the repo except for the addition of (L|l)indane in the new file.  I think the idea is to make a PR with the new file, merge it, and then release bioresources anew with the update.  It would be a new number like 1.1.27.

**Comment by Hasnae-25** [comment] 2020-01-29 09:58
Hi,

@MihaiSurdeanu @kwalcock, Please, can you let me know when it is released? Kind regards, Hasnae

**Comment by MihaiSurdeanu** [comment] 2020-01-30 00:05
@kwalcock: can you please release bioresources 1.1.27?

**Comment by kwalcock** [comment] 2020-01-30 15:29
With the updated PubChem.tsv.gz, I assume.  Working on it...

**Comment by kwalcock** [comment] 2020-01-30 16:29
The procedure I outlined above is not complete.  I neglected to run ner_kb.sh.  Therefore do not use 1.1.27.  It will be 1.1.28 instead.

**Comment by kwalcock** [comment] 2020-01-30 18:13
I reran the program and was expecting only the Simple_chemical.tsv file to change, but was surprised when most of the files did.  It looks like all the changes are related to whitespace.  Not all the changes look legitimate.  Here are some questionable ones:

**Family.tsv**

new: Lecithin : cholesterol and phospholipid :d iacylglycerol acyltransferase
old: Lecithin : cholesterol and phospholipid : diacylglycerol acyltransferase

new: ATP :d ephospho-CoA triphosphoribosyl transferase
old: ATP : dephospho-CoA triphosphoribosyl transferase

new: CDP-Glycerol :P oly ( glycerophosphate ) glycerophosphotransferase
old: CDP-Glycerol : Poly ( glycerophosphate ) glycerophosphotransferase

**Cellular_component.tsv**

new: T =p seudo3 icosahedral viral capsid
old: T = pseudo3 icosahedral viral capsid

**Site.tsv**

new: Myristoyl-CoA :p rotein N-myristoyltransferase , C-terminal
old: Myristoyl-CoA : protein N-myristoyltransferase , C-terminal

new: Thiol :d isulfide interchange protein DsbD , N-terminal domain
old: Thiol : disulfide interchange protein DsbD , N-terminal domain

The whitespace is generally around punctuation.  I'm not sure about the ones that don't break up words.  Attached are two of the smallest files for comparison.


[Species-old.txt](https://github.com/clulab/reach/files/4135578/Species-old.txt)
[Species-new.txt](https://github.com/clulab/reach/files/4135585/Species-new.txt)

**Comment by Hasnae-25** [comment] 2020-02-05 11:47
Hi @kwalcock @MihaiSurdeanu Is the file released now? Thanks in advance!

Kind regards, Hasnae

**Comment by kwalcock** [comment] 2020-02-05 17:44
@MihaiSurdeanu, did you have a chance to think about my previous message?  Is there a good way to confirm that there isn't a problem?  FWIW, the reach and processors tests still pass when I publish bioresources locally with the change and then depend on it.  However, I doubt that the tests are sensitive enough to notice small problems in the data.

**Comment by MihaiSurdeanu** [comment] 2020-02-06 00:30
@kwalcock: this is caused by the change in tokenizers in processors. The examples you included are not ideally handled, but they are not that important. I propose to release.

**Comment by Hasnae-25** [comment] 2020-02-06 10:29
@MihaiSurdeanu @kwalcock Let me know  when the file is released.Thanks in advance! Kind regards, Hasnae

**Comment by kwalcock** [comment] 2020-02-06 16:32
bioresources 1.1.28 has been released.  Others may notice it being accessible before I do.  Does reach need to be updated to match?

**Comment by MihaiSurdeanu** [comment] 2020-02-06 23:57
Yes, please!

**Comment by kwalcock** [comment] 2020-02-07 22:22
reach v1.5.1 has been updated to use the new bioresources v1.1.28.

**Comment by MihaiSurdeanu** [comment] 2020-02-14 01:36
@kwalcock: the differences you observed above in tokenization are caused by incorrect tokenization of emoticons (e.g., :d) in processors. I'm working on fixing that. Afterwards, we should release bioresources.

**Comment by MihaiSurdeanu** [comment] 2020-02-14 03:29
@kwalcock : This has been addressed by PR #362 in processors.
When you have a chance, can you please release a new version of bioresources? 
This not urgent at all. I think the tokenization differences do not have any major impact. They are just annoying.

**Comment by kwalcock** [comment] 2020-02-14 03:40
Will do.  Thanks for checking out that problem.

**Comment by kwalcock** [comment] 2020-02-17 22:29
bioresources has been updated to 1.1.29 and appears to be accessible already.  @Hasnae-25, fyi.

**Closed by kwalcock** 2020-02-17 22:29 UTC

**Comment by MihaiSurdeanu** [comment] 2020-02-17 23:26
Thank you!
