### ISSUE TITLE
Feedback on REACH extractions of complexes/binding events on Batch 4 corpus

### ISSUE THREAD

**Issue by johnbachman** [clulab/reach#321] opened 2016-08-19 21:43 UTC
Dear REACH team,

I've been exploring the results of running REACH on the Batch 4 corpus and had some feedback to share. I wanted to get an overall sense of the expected accuracy of reading, and statements about protein complexes are among the easiest to score because they are straightforward to match against databases (e.g., BioGrid).

I filtered out the statements extracted by REACH from the Batch 4 papers and pulled out the Complex statements involving grounded human genes, of which there were 135. (I should mention that in processing results from REACH I used a grounding table mapping strings to identifiers very similar in spirit to your grounding override resource (which I did not use); I manually curated a table with about 630 entries from the Batch 4 corpus and a larger corpus of ~7k papers focused around Ras).

Then I checked how many of these 135 grounded Complex statements had corresponding entries in BioGrid. There turned out to be 70, or roughly 50%.

Then I took the remaining 65 statements and manually scored them for correctness based on an examination of the sentences. I found about 58% of this non-Biogrid fraction to be correct. Not surprisingly, the more sentences associated with a statement after combining duplicates, the more likely the statement was to be correct. As I scored the statements, I pulled them out to feed back to you guys for improvements. I hope this helps. Here is an enumeration of various errors I identified in extracting complexes from the sentences in the Batch 4 papers:

In the following sentence, REACH extracts Complex(EGF, AREG), presumably from the phrase "amphiregulin and heparin binding EGF". However, "heparin binding EGF" is the name of a gene, HBEGF. The same sentence also yields erroneous binding between TGFA and NRG1 and other pairs of ligands::

    [Evidence(reach, PMID23027125, {'cell_type': None, 'organ': None, 'tissue': None, 'location':[u'go:GO:0005576'], 'cell_line': None, 'species': [u'taxonomy:9606']}, Three of the family members, except HER2 (XREF_BIBR), are activated by ligand binding (EGF, TGFalpha, heregulin, amphiregulin and heparin binding EGF) to the extracellular region, while HER2 is a constitutively active protein.)]
    
The following are extracted as PREX-1 binds PTEN, despite the fact that the sentences mainly describe negative results of looking for binding between these two proteins::

    [Evidence(reach, PMID25284585, {'cell_type': None, 'organ': None, 'tissue': None, 'location': None, 'cell_line': [u'cellosaurus:CVCL_0588'], 'species': [u'taxonomy:9606']}, The P-REX1 homolog P-REX2a binds PTEN and inhibits its lipid phosphatase activity [XREF_BIBR].),
    Evidence(reach, PMID25284585, {'cell_type': None, 'organ': None, 'tissue': None, 'location': None, 'cell_line': [u'cellosaurus:CVCL_0553'], 'species': [u'taxonomy:9606']}, Since the P-REX1 homologue P-REX2a was found to bind PTEN [XREF_BIBR], we considered that PTEN may bind and stabilize P-REX1.),
    Evidence(reach, PMID25284585, {'cell_type': None, 'organ': None, 'tissue': None, 'location': None, 'cell_line': [u'cellosaurus:CVCL_0588'], 'species': [u'taxonomy:9606']}, While we detected a low level of P-REX1 and PTEN binding in situ, in vitro and in situ analyses did not reveal an effect of P-REX1 on PTEN phosphatase activity (data not shown).),
    Evidence(reach, PMID25284585, {'cell_type': None, 'organ': None, 'tissue': None, 'location': None, 'cell_line': [u'cellosaurus:CVCL_0553'], 'species': [u'taxonomy:9606']}, However, we detected only very low levels of P-REX1 and PTEN interaction in cells (data not shown).)]

The following sentences yield extractions of a binding event between HSPB6 ("HSP20") and the gene SDHB (Uniprot P21912, a mis-grounding of "IP", which refers here to immunoprecipitation)::

    [Evidence(reach, PMID24223153, {'cell_type': None, 'organ': None, 'tissue': None, 'location': [u'go:GO:0005623'], 'cell_line': None, 'species': [u'taxonomy:9986']}, (B and C) The empty vector transfected (lanes 1) and HSP20 overexpressing (lanes 2) HuH7 cell lysates were immunoprecipitated (IP) with antibodies for HSP20 (B) or normal rabbit IgG (C), followed by Western blotting (WB) using PI3K p85 antibodies, PI3K p110alpha antibodies, PI3K p110beta antibodies or HSP20 antibodies.),
     Evidence(reach, PMID24223153, {'cell_type': None, 'organ': None, 'tissue': None, 'location': [u'go:GO:0005623'], 'cell_line': None, 'species': [u'taxonomy:9986']}, The empty vector and HSP20 overexpressing HuH7 cell lysates were immunoprecipitated (IP) with antibodies for AKT, ERK, MEK and normal rabbit IgG followed by Western blotting (WB) using HSP20 antibodies (lanes 3 and 4).),
    Evidence(reach, PMID24223153, {'cell_type': None, 'organ': None, 'tissue': None, 'location': [u'go:GO:0005623'], 'cell_line': None, 'species': [u'taxonomy:9986']}, (A) The empty vector transfected (lane 1) and HSP20 overexpressing (lane 2) HuH7 cell lysates were immunoprecipitated (IP) with antibodies for PI3K p85, PI3K p110alpha and PI3K p110beta subunits, followed by Western blotting (WB) using HSP20 antibodies.)]

Extracted as an interaction between HSPB6 and itself::
    
    [Evidence(reach, PMID24223153, {'cell_type': None, 'organ': None, 'tissue': None, 'location': [u'go:GO:0005623'], 'cell_line': None, 'species': [u'taxonomy:10090']}, The binding partner (s) of HSP20 and their interaction (s) might be dependent on the cell types.),
    Evidence(reach, PMID24223153, {'cell_type': None, 'organ': None, 'tissue': None, 'location': [u'go:GO:0005623'], 'cell_line': None, 'species': [u'taxonomy:9606']}, In cardiomyocytes, HSP20 reportedly interacts with phosphorylated AKT and maintains it in its phosphorylated state.)]

The following sentences yield an erroneous binding event between RAC1 and CDC42, even though they refer to either RAC1 *or* CDC42 binding p110beta::

    [Evidence(reach, PMID23706742, {'cell_type': None, 'organ': None, 'tissue': None, 'location': None, 'cell_line': None, 'species': [u'taxonomy:10090']}, We did not study monomeric p85, which has not been found in living cells (XREF_BIBR), but our biochemical data strongly argue against an involvement of p85 in the RAC and CDC42-p 110beta interaction, because (1) RAC1 and CDC42 do not interact with p110alpha and p85 or p110delta and p85, (2) RAC1 and CDC42 bind normally to p110beta in the absence of the p85 BH domain, and (3) RBD point mutations abrogate RAC1 and CDC42 binding to p110beta in complex with full-length p85.),
    Evidence(reach, PMID23706742, {'cell_type': None, 'organ': [u'uberon:UBERON:0002488'], 'tissue': None, 'location': None, 'cell_line': None, 'species': [u'taxonomy:10090']}, To further corroborate these findings, we generated 43 single point mutations covering 37 residues across the p110beta RBD and assayed these mutants for binding to RAC1 and CDC42 (XREF_FIGD, XREF_FIGA, and S3B).)]

This one yields binding between MAZ and MAZ (SAF-1 is a synonym for MAZ, hence the redundancy here). However, the sentence refers to binding of this protein to the promoter of Ras::

    [Evidence(reach, PMID25449683, {'cell_type': None, 'organ': None, 'tissue': None, 'location': None, 'cell_line': None, 'species': [u'taxonomy:10090']}, Our finding of the G rich sequences and a possible G-quadruplex structure in Ras gene promoter as a site of interaction of SAF-1 and MAZ and involvement of such interaction in ras expression could have a significant impact in understanding the role of SAF-1 and MAZ in breast cancer and perhaps in other cancer as well due to ubiquitous presence of Ras in many cancers and its direct link to SAF-1 and MAZ which is revealed in the current study.)]

Yields erroneous binding of BCR to BCR::

    [Evidence(reach, PMID10770799, {'cell_type': [u'cl:CL:0000236'], 'organ': None, 'tissue': None, 'location': [u'go:GO:0005694'], 'cell_line': None, 'species': [u'taxonomy:9606']}, Human germinal center B cells show increased Bam32 expression, and resting B cells rapidly upregulate expression of Bam32 after ligation of CD40, but not immunoglobulin M. Bam32 is tyrosine phosphorylated upon B cell antigen receptor (BCR) ligation or pervanadate stimulation and associates with phospholipase Cgamma2.)]

The following is extracted as an interaction between PLK1 and TIAM1, even though the sentence states only that "we tested whether...". This appears to be recurring error, with the pattern "...whether X binds/interacts/associates with Y" being extracted as "X binds Y". However, for sentences of the form "We tested whether X interaction with Y does Z" it seems reasonable to extract "X interacts with Y".

    [Evidence(reach, PMID26078008, {'cell_type': None, 'organ': None, 'tissue': None, 'location': [u'go:GO:0005694'], 'cell_line': [u'cellosaurus:CVCL_3540'], 'species': [u'taxonomy:10090']}, As S1466 creates a potential Polo-box binding site (S-S and T-P) when phosphorylated, and Plk1 plays multiple roles in regulating centrosome separationXREF_BIBRXREF_BIBRXREF_BIBR, we also tested whether Plk1 interacts with Tiam1, and whether mutation of S1466 might affect this.)]

In the following, "AC core" is misgrounded to the gene ASAH1 to yield a binding event between PPP2CA and ASAH1. However, "AC core" refers to the subunits making up the PP2A complex (see http://www.ncbi.nlm.nih.gov/pubmed/22315229)::

    [Evidence(reach, PMID20473327, {'cell_type': None, 'organ': None, 'tissue': None, 'location': None, 'cell_line': None, 'species': [u'taxonomy:9606']}, No interaction was detected between either exogenous protein and the endogenous B56gamma, suggesting that the inhibitory mechanism of F395C overexpression is probably through competitive binding to the AC core of PP2A or some unknown factors.)]
    
In this sentence p27 is identified as binding to the gene MCAT, due to misgrounding of the abbreviation "MT" (which refers to microtubules). The correct entity for the binding event is stathmin (a gene family)::

    [Evidence(reach, PMID21423803, {'cell_type': None, 'organ': None, 'tissue': None, 'location': None, 'cell_line': None, 'species': [u'taxonomy:9606']}, It has been demonstrated that p27 C-terminal tail binds also the MT destabilizing protein stathmin XREF_BIBR-XREF_BIBR.)]

Erroneous binding between BCR and CD40::

    [Evidence(reach, PMID10770799, {'cell_type': [u'cl:CL:0000236'], 'organ': None, 'tissue': None, 'location': [u'go:GO:0005634'], 'cell_line': None, 'species': [u'taxonomy:10090']}, Modulation of BCR induced NF-AT activation by Bam32 could have important functional consequences for B cells, since B cells from NF-ATc-deficient mice have diminished proliferative responses to a variety of stimuli, including BCR or CD40 ligation 3940.)]
    
Erroneous extraction of binding between PRL3 and Src::

    [Evidence(reach, PMID23691193, {'cell_type': None, 'organ': None, 'tissue': None, 'location': None, 'cell_line': [u'cellosaurus:CVCL_0546'], 'species': [u'taxonomy:10090']}, Although these results do not indicate whether PRL-3 is a direct or indirect target of Src, and indeed unequivocal demonstration of a direct relationship between kinase and substrate in cells is technically not feasible with currently available technology, they do indicate that Src can act upstream of PRL-3 and is sufficient to mediate its tyrosine phosphorylation in cells.)]

"Son of sevenless" misgrounded to the gene SON instead of SOS (gene family)::

    [Evidence(reach, PMID26617336, {'cell_type': None, 'organ': None, 'tissue': None, 'location': None, 'cell_line': None, 'species': [u'taxonomy:10090']}, Grb2 binds to the guanine nucleotide exchange factor Son of Sevenless (SOS), which promotes the removal of GDP from Ras for GTP, a necessary step in the re-activation of RasXREF_BIBR.)]

Erroneous binding between RHOG and RHOA::

    [Evidence(reach, PMID23706742, {'cell_type': None, 'organ': None, 'tissue': None, 'location': None, 'cell_line': None, 'species': [u'taxonomy:10090']}, Weaker binding to RHOG and minimal binding to RHOA was also observed (XREF_FIGE).)]

"GST-p85" erroneously grounded to CBFA2T2, instead of p85 (protein family). In general, epitope tag prefixes such as GST, FLAG, His, etc. for fusion proteins should be stripped off during the entity extraction step::

    [Evidence(reach, PMID12515821, {}, GST-p85 or either of its SH2 domains could bind to Abi1 (XREF_FIG B) and to various pTyr containing proteins, one of which co-migrated with Abi1 (unpublished data).)]

Erroneously extracts binding between RAC1 and SYNJ1, despite the "not"::

    [Evidence(reach, PMID23076136, {'cell_type': None, 'organ': None, 'tissue': None, 'location': [u'go:GO:0030136'], 'cell_line': None, 'species': [u'taxonomy:9606']}, The C-terminal domain of SYNJ2, but not SYNJ1, also contains a Rac1 binding domain.XREF _ BIBR SYNJ1 and 2 play diverse roles in clathrin mediated endocytosis.)]

Yields a binding event between TGF-beta and PAK2, even though the sentence doesn't support that::

    [Evidence(reach, PMID22880011, {'cell_type': [u'cl:CL:0008019'], 'organ': None, 'tissue': None, 'location': None, 'cell_line': None, 'species': [u'taxonomy:4932']}, Pak2 is specifically activated by TGF-beta only in mesenchymal cells, as the result of phosphatidylinositol 3-kinase (PI3K) activation and may be associated with TGF-beta activation of Ras XREF_BIBR, XREF_BIBR, XREF_BIBR.)]

Erroneous binding between p110alpha and p110gamma, despite the fact that it's the interactions with those proteins with Ras that are being referred to::

    [Evidence(reach, PMID23706742, {'cell_type': None, 'organ': None, 'tissue': None, 'location': None, 'cell_line': [u'cellosaurus:CVCL_6249'], 'species': [u'taxonomy:10090']}, Similar affinities have been reported for the RAS-p110alpha and RAS-p110gamma interactions (XREF_BIBR; XREF_BIBR), indicating that RAC1 and CDC42 areplausible RBD interactors of p110beta.)]

**Comment by hickst** [comment] 2016-08-19 22:00
My first thought is that you may have picked a very bad domain to evaluate Reach reading since Reach currently does not identify and extract either Complexes or Genes as basic entities. Your feedback may be very valuable, however, in identifying and providing motivation for prioritizing where Reach should be extended in the near future.

**Comment by MihaiSurdeanu** [comment] 2016-08-20 02:12
Thanks John!
This is actually great feedback! Tom is correct that we don't extract named complexes as atomic entities (unless they appear in Uniprot), but we do extract Binding events. All the issues you report are bugs in that component. We will begin addressing them soon.
We'll probably break this issue into several focused ones, so don't panic if this one dissappears :)
Mihai

**Comment by johnbachman** [comment] 2016-08-20 02:15
I should clarify--none of these extractions depend on representing/identifying Complexes or Genes as basic entities. I think the confusion may have arisen from my use of the term "Complex", which is the name of the INDRA class representing binding events, and from my reference to "grounding to human genes"--I really just mean human proteins. I use the HGNC names for clarity/transparency.

So, what I'm talking about here are extractions by REACH of binding events between human proteins. Since you have just run REACH on this same corpus of 100 papers for the evaluation, take a look at the binding events extracted--you will presumably see these same sentences in your results.

Also, I should also emphasize that REACH actually does very well, with close to 80% precision in extracting binding events! As I mentioned above, over 50% of the binding events can be mapped directly to curated interactions in BioGrid (which we can consider a gold standard for this purpose), and of the remaining, 58% were scored manually by me as being correct, for an overall precision of 78%.

The examples given here are of the relatively small fraction (~22%) that I scored as being incorrect, and are provided in hopes of helping to identify patterns.

**Comment by johnbachman** [comment] 2016-08-20 02:27
Mihai--our comments crossed :) Yes, I expected that you guys would know better how to break this up into actionable issues.

**Comment by johnbachman** [comment] 2016-08-20 02:29
Also, I see now that I explicitly wrote "statements about protein complexes"--that was very misleading. I was referring specifically to binding events.

**Comment by MihaiSurdeanu** [comment] 2016-09-07 21:18
@bgyori, @johnbachman: on the "RAC1 or CDC42 binding p110beta" example, how can you say that it's not a complex with 3 elements? Domain knowledge?

**Comment by MihaiSurdeanu** [comment] 2016-09-07 21:23
@bgyori, @johnbachman: in the ""we tested whether..." examples, did you check if these interactions are marked as "is_hypothesis = true"? They should. If so, you can just remove all hypothesized extractions from your model

**Comment by danebell** [comment] 2016-09-07 21:25
Some of these are caused by allowing a binding to have themes with the same grounding. This can be fixed by adding an `if` statement to guarantee unequal grounding ids here: https://github.com/clulab/reach/blob/1b70b3245a0ae252837103b5e60b8ee9a7bc34bb/src/main/scala/org/clulab/reach/darpa/DarpaActions.scala#L237

**Comment by MihaiSurdeanu** [comment] 2016-09-07 21:35
Closing this issue, because it's been broken in multiple simpler ones.
Also, I can't scroll this much :)

**Closed by MihaiSurdeanu** 2016-09-07 21:35 UTC

**Comment by johnbachman** [comment] 2016-09-08 02:16
@MihaiSurdeanu : On your question about Rac1/Cdc42 binding...that's an interesting point, I hadn't considered that possibility. I guess domain knowledge comes in in at least two ways (without me even having to read the whole paper).

1. Rac and Cdc42 are both members of the same protein family (Rho family GTPases), so it's likely that they would have similar interactions with PI3K, making them competitive binders--not binding at the same time.

2. Experimental procedures for looking at binding (e.g., immunoprecipitation) are typically binary. You pull down protein X and look whether protein A, or protein B is attached (by Western blot). You don't get information on whether A and B are attached to X at the same time or not. So assuming A *or* B binding to X would be the minimal interpretation of the data.
