### ISSUE TITLE
ContextEngine warnings?

### ISSUE THREAD

**Issue by myedibleenso** [clulab/reach#331] opened 2016-08-25 19:41 UTC
I was running reach on some papers where I encountered these warnings:
```
WARNING: key (Organ,uaz:UAZ02289) not found in the context vocabulary
WARNING: key (CellType,uaz:UAZ02290) not found in the context vocabulary
WARNING: key (Organ,uaz:UAZ02289) not found in the context vocabulary
WARNING: key (CellType,uaz:UAZ02290) not found in the context vocabulary
```

Should I be concerned, @enoriega?  Unfortunately, I can't tell you which paper is to blame, as I was running reach over 1000 papers...

**Comment by enoriega** [comment] 2016-08-25 20:35
@myedibleenso: What version of bioresources is being used with this build of reach?

**Comment by myedibleenso** [comment] 2016-08-25 21:21
v1.1.15 (same as the `master` branch of reach).

**Comment by myedibleenso** [comment] 2016-08-25 21:22
Actually, I'm seeing a lot more of these warnings as this jobs chugs along.

**Comment by enoriega** [comment] 2016-08-29 17:31
The reason of why this warning gets printed is because the ids, for example `uaz:UAZ02290` aren't in any of the KBs of bioresources.

I'm not sure how that ID came to existence. Is it possible that `uaz:UAZ02290` is being generated by the CRF?

@hickst Is it possible that a CRF detected mention is hiding the a cell type or organ that matches the same text because proteins have higher priority than organs or cell types?

**Comment by hickst** [comment] 2016-08-29 17:42
> The reason of why this warning gets printed is because the ids, for example uaz:UAZ02290 aren't in any of the KBs of bioresources.

That's correct. If a string is not found in the KBs, it gets a "default" ID of this form from grounding.

> I'm not sure how that ID came to existence. Is it possible that uaz:UAZ02290 is being generated by the CRF?

If a string is not found in the KBs, it gets a "default" ID of this form from grounding.

> Is it possible that a CRF detected mention is hiding the a cell type or organ that matches the same text because proteins have higher priority than organs or cell types?

Yes and no. The NER labeling (which uses CRF and the NER override KB) **TELL** grounding which KB to lookup the string in. So, if the NER labeling says a string *xyz* is a protein, it will be looked up in the protein table.

Step 1 would be to look at the labels on the problematic mentions to see how the NER is labeling them. If they have the correct label, then the problem is in grounding.

**Comment by enoriega** [comment] 2016-08-29 17:45
In these particular examples, the labels are `Organ` and `CellType`, which are the first element of the tuples:

```(Organ,uaz:UAZ02289)
(CellType,uaz:UAZ02290)```

The IDs, though, are not coming from either Uberon or Cellosaurus. Since they are labeled as a context type, they make their way through the context engine, but can't be fetched from the tsv files and print a warning

**Comment by MihaiSurdeanu** [comment] 2016-09-28 20:59
closing for now. probably a configuration issue.

**Closed by MihaiSurdeanu** 2016-09-28 20:59 UTC
Labels: context

**Comment by hickst** [comment] 2016-09-29 21:22
Can you elaborate on the configuration issue?
Data point: in the recent BigRun we got 29,968 of these warnings.
